"""
Daily Briefing for AI Employee

Generates daily summary of:
- Yesterday's accomplishments
- Today's priorities
- Pending items requiring attention

Silver Tier Implementation

Usage:
    python scripts/daily_briefing.py
"""

import sys
from pathlib import Path
from datetime import datetime, timedelta


def generate_daily_briefing(vault_path: Path) -> str:
    """Generate daily briefing content."""

    done_dir = vault_path / 'Done'
    needs_action = vault_path / 'Needs_Action'
    accounting_dir = vault_path / 'Accounting'

    # Count completed tasks (today/yesterday)
    yesterday = datetime.now() - timedelta(days=1)

    completed_yesterday = []
    if done_dir.exists():
        for file in done_dir.glob('*.md'):
            try:
                mtime = datetime.fromtimestamp(file.stat().st_mtime)
                if mtime.date() == yesterday.date():
                    completed_yesterday.append(file.name)
            except Exception:
                continue

    # Get accounting summary
    accounting_summary = ""
    if accounting_dir.exists():
        current_month_file = accounting_dir / 'Current_Month.md'
        if current_month_file.exists():
            content = current_month_file.read_text(encoding='utf-8')
            # Extract total if available
            if 'Total:' in content:
                for line in content.split('\n'):
                    if 'Total:' in line:
                        accounting_summary = line.strip()
                        break

    # Count pending items
    pending_items = []
    if needs_action.exists():
        pending_items = list(needs_action.glob('*.md'))

    # Generate briefing
    today = datetime.now().strftime('%Y-%m-%d')

    briefing = f'''# Daily Briefing - {today}

## Yesterday's Accomplishments

'''

    if completed_yesterday:
        for task in completed_yesterday[:10]:  # Limit to 10
            briefing += f"- [x] {task}\n"
    else:
        briefing += "*No tasks completed yesterday*\n"

    briefing += f'''
## Today's Priorities

1. Process pending items in Needs_Action ({len(pending_items)} items)
2. Review and approve pending approvals
3. Check Gmail for urgent messages
4. Monitor LinkedIn for engagement

## Pending Items

'''

    if pending_items:
        briefing += "| Item | Type | Priority |\n"
        briefing += "|------|------|----------|\n"
        for item in pending_items[:10]:
            try:
                content = item.read_text(encoding='utf-8')
                # Extract type and priority
                item_type = "Unknown"
                priority = "Normal"
                for line in content.split('\n')[:15]:
                    if 'type:' in line:
                        item_type = line.split(':')[1].strip()
                    if 'priority:' in line:
                        priority = line.split(':')[1].strip()
                briefing += f"| {item.name[:40]}... | {item_type} | {priority} |\n"
            except Exception:
                continue
    else:
        briefing += "*No pending items! 🎉*\n"

    briefing += f'''
## Accounting Summary

{accounting_summary if accounting_summary else "*No transactions this month*"}

## Notes

*Add notes for today*

---
*Generated by AI Employee Daily Briefing - {datetime.now().strftime('%Y-%m-%d %H:%M')}*
'''

    return briefing


def main():
    """Main entry point."""
    # Get vault path
    if len(sys.argv) > 1:
        vault_path = Path(sys.argv[1])
    else:
        vault_path = Path(__file__).parent.parent

    print("=" * 60)
    print("AI Employee - Daily Briefing")
    print("=" * 60)

    # Generate briefing
    briefing = generate_daily_briefing(vault_path)

    # Save to Briefings folder
    briefings_dir = vault_path / 'Briefings'
    briefings_dir.mkdir(parents=True, exist_ok=True)

    today = datetime.now().strftime('%Y-%m-%d')
    briefing_file = briefings_dir / f'{today}_Daily.md'

    briefing_file.write_text(briefing, encoding='utf-8')

    print(f"\n✓ Daily Briefing created: {briefing_file}")
    print(f"\nSummary:")
    print(f"  - Saved to: Briefings/{briefing_file.name}")

    # Update Dashboard
    dashboard_path = vault_path / 'Dashboard.md'
    if dashboard_path.exists():
        content = dashboard_path.read_text(encoding='utf-8')
        if '| Last Briefing |' in content:
            import re
            content = re.sub(
                r'\| Last Briefing \|.*\|',
                f'| Last Briefing | {today} |',
                content
            )
            dashboard_path.write_text(content, encoding='utf-8')
            print(f"  - Dashboard updated")

    print("\n" + "=" * 60)


if __name__ == '__main__':
    main()
